
const TODO_ADD = "TODO_ADD";
const TODO_TOGGLE = "TODO_TOGGLE";


const FILTER_SET = "FILTER_SET";
const NOTIFICATION_HIDE = "NOTIFICATION_HIDE";

export {TODO_ADD, TODO_TOGGLE, FILTER_SET, NOTIFICATION_HIDE}